site_name: Aplicaciones Web
site_description: Logra los resultados de aprendizaje del módulo, trabajando por proyectos.
site_author: Jose Robledano Garcia
site_dir: resultado
site_url: https://sever8a.github.io/awe/
docs_dir: appweb


nav: 
    - "Las aplicaciones web": "index.md"
    - "MediaWiki": "mediawiki.md"
    - "WordPress": "wordpress.md"
    - "Joomla": "joomla.md"
    - "HTML": "html.md"
    - "CSS": "css.md"
    
theme:
    name: 'material'
    features:
        - navigation.expand

markdown_extensions:
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true
    - def_list
    - footnotes
    - pymdownx.tasklist:
        custom_checkbox: true