site_name: Aplicaciones Web
site_description: Logra los resultados de aprendizaje del m칩dulo, trabajando por proyectos.
site_author: Jose Robledano Garcia
site_dir: resultado
site_url: https://sever8a.github.io/awe/
docs_dir: appweb


nav: 
    - "Las aplicaciones web":
        - "index.md"
        - "Reto - 1: Aplicaciones Web": "reto1.md"
    - "MediaWiki": "mediawiki.md"
    - "WordPress": "wordpress.md"
    - "Joomla": 
        - "joomla.md"
        - "Montar un sitio": "joomla_sitio.md"
    - "Moodle": "moodle.md"
    - "HTML": "html.md"
    - "CSS": "css.md"
    
theme:
    name: 'material'
    features:
        - navigation.expand

extra:
    consent:
        title: Cookie consent
        description: >-
            Esta p치gina de apuntes utiliza cookies para reconocer las visitas, medir la efectividad de la documentaci칩n
            y averiguar si encuentras aquello que buscas o c칩mo has llegado a estos apuntes.
            Con tu consentimiento, me ayudas a mejorar estos materiales.
    analytics:
        provider: google
        property: G-Y671WB1DQM

markdown_extensions:
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true
    - def_list
    - footnotes
    - pymdownx.tasklist:
        custom_checkbox: true